### ISSUE TITLE
output error

### ISSUE THREAD

**Issue by Alihamdy2496** [mabaorui/NeuralPull-Pytorch#1]
thank you for sharing your amazing work

I test your code with the given gargoyle example and got correct output, and when I tried my point cloud it gave me this message

        Data not found. Processing data...
        Traceback (most recent call last):
          File "run.py", line 190, in <module>
            runner = Runner(args, args.conf, args.mode)
          File "run.py", line 38, in __init__
            self.dataset_np = DatasetNP(self.conf['dataset'], args.dataname)
          File "/content/NeuralPull-Pytorch/models/dataset.py", line 93, in __init__
            self.object_bbox_min = np.array([np.min(self.point[:,0]), np.min(self.point[:,1]), np.min(self.point[:,2])]) -0.05
          File "<__array_function__ internals>", line 6, in amin
          File "/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py", line 2880, in amin
            keepdims=keepdims, initial=initial, where=where)
          File "/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
            return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
        ValueError: zero-size array to reduction operation minimum which has no identity

my point cloud has 5008596 points with the coordinates , the normal and the colours

ply
format binary_little_endian 1.0
comment Created by Open3D
element vertex 5008596
property double x
property double y
property double z
property double nx
property double ny
property double nz
property uchar red
property uchar green
property uchar blue
end_header

**Comment by junshengzhou** [comment]
Hi, thanks for your interest!

You can try to adjust the number of generated query points since the size of your points cloud is too large.
The code lies in the `'models/dataset.py'`, line 35:
`QUERY_EACH = 1000000//POINT_NUM_GT` -> set 1000000 to 2*1e7 may solve your problem.

**Comment by Alihamdy2496** [comment]
thank you for your time 

I modified it, but it seems that my point cloud is too large to work with 

        Data not found. Processing data...
        Traceback (most recent call last):
          File "run.py", line 190, in <module>
            runner = Runner(args, args.conf, args.mode)
          File "run.py", line 38, in __init__
            self.dataset_np = DatasetNP(self.conf['dataset'], args.dataname)
          File "/content/NeuralPull-Pytorch/models/dataset.py", line 85, in __init__
            process_data(self.data_dir, dataname)
          File "/content/NeuralPull-Pytorch/models/dataset.py", line 58, in process_data
            nearest_idx = search_nearest_point(torch.tensor(tt[j]).float().cuda(), torch.tensor(pointcloud).float().cuda())
          File "/content/NeuralPull-Pytorch/models/dataset.py", line 11, in search_nearest_point
            point_batch = point_batch.unsqueeze(1).repeat(1, num_point_gt, 1)
        RuntimeError: CUDA out of memory. Tried to allocate 34.48 GiB (GPU 0; 14.76 GiB total capacity; 5.01 MiB already allocated; 13.52 GiB free; 22.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by mabaorui** [comment]
This point cloud is too large for the GPU, try putting it on the CPU or downsampling the point cloud.

**Comment by lemonsstyle** [comment]
> thank you for your time
> 
> I modified it, but it seems that my point cloud is too large to work with
> 
> ```
>     Data not found. Processing data...
>     Traceback (most recent call last):
>       File "run.py", line 190, in <module>
>         runner = Runner(args, args.conf, args.mode)
>       File "run.py", line 38, in __init__
>         self.dataset_np = DatasetNP(self.conf['dataset'], args.dataname)
>       File "/content/NeuralPull-Pytorch/models/dataset.py", line 85, in __init__
>         process_data(self.data_dir, dataname)
>       File "/content/NeuralPull-Pytorch/models/dataset.py", line 58, in process_data
>         nearest_idx = search_nearest_point(torch.tensor(tt[j]).float().cuda(), torch.tensor(pointcloud).float().cuda())
>       File "/content/NeuralPull-Pytorch/models/dataset.py", line 11, in search_nearest_point
>         point_batch = point_batch.unsqueeze(1).repeat(1, num_point_gt, 1)
>     RuntimeError: CUDA out of memory. Tried to allocate 34.48 GiB (GPU 0; 14.76 GiB total capacity; 5.01 MiB already allocated; 13.52 GiB free; 22.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> ```

Hello friend, I'm also watching point cloud gridding. The data I need to process is very large, similar to an indoor scene.Do you have any recommendations？ Thanks！
